# Utiliza la imagen base de Ubuntu 20.04
FROM ubuntu:20.04

# Actualiza los repositorios e instala Git
RUN apt-get update && apt-get install -y git

# Comando por defecto al iniciar el contenedor
CMD ["bash"]